version: "2.2"

services:
  migrator:
    build: ./api
    command: python manage.py migrate
    depends_on:
      - postgres

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - migrator
    environment:
      - DEBUG=True
    restart: unless-stopped

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=yata
      - POSTGRES_PASSWORD=password-is-yep-another-todo-app
      - POSTGRES_DB=yatadb
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped

  ui:
    build: ./ui
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
