# Generated by Django 3.0.6 on 2020-05-28 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('our_jwt_token', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistedtoken',
            old_name='token',
            new_name='token_id',
        ),
        migrations.AlterUniqueTogether(
            name='blacklistedtoken',
            unique_together={('token_id', 'user')},
        ),
    ]
